version: '3'

services:
  code-challange:
    container_name: code-challange-api
    image: node:alpine3.16
    working_dir: /usr/judge
    restart: always
    command: sh -c "yarn --only=prod && yarn debug"
    ports:
      - 8080:8080
    volumes:
      - .:/usr/judge