version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongodb
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  code-challange:
    container_name: code-challange-api
    image: node:alpine3.16
    working_dir: /usr/judge
    restart: always
    command: sh -c "yarn --check-files && yarn debug"
    ports:
      - 8080:8080
    volumes:
      - .:/usr/judge
    depends_on:
      - mongodb